export type GameKitId =
  | "classic"
  | "quick"
  | "free-for-all"
  | "custom"
  | "birthday-party"
  | "city-explorer"
  | "office-team-building"
  | "kids-indoor"
  | "classroom"
  | "at-home-adventure"
  | "park-playground"
  | "neighborhood-stroll"
  | "holiday-dinner"
  | "new-team-welcome"
  | "solo-photo-walk";

export type GameKitTask = {
  id: string;
  title: string;
  description: string;
  icon: string;
  free?: boolean;
  sortOrder: number;
};

export type GameKit = {
  id: Exclude<GameKitId, "classic" | "custom">;
  name: string;
  gameName: string;
  category: string;
  setting: string;
  ageLabel: string;
  summary: string;
  detail: string;
  featured?: boolean;
  searchTags: readonly string[];
  playerLabel: string;
  durationLabel: string;
  playMode: "teams" | "individual";
  winCondition: "blackout" | "bingo";
  boardSize: 3 | 4 | 5;
  boardMode: "shared" | "randomized";
  freeSpace: boolean;
  proofMode: "required" | "optional" | "none";
  approvalMode: "host" | "automatic";
  timerMode: "none" | "duration" | "schedule";
  timerDurationMinutes: number;
  teamCount: number;
  tasks?: readonly GameKitTask[];
};

const birthdayTasks = tasks([
  ["birthday-group-photo", "Birthday Group Photo", "Get everyone together for a birthday photo.", "Camera"],
  ["best-party-hat", "Best Party Hat", "Find or make the best party hat in the room.", "HardHat"],
  ["birthday-dance", "Birthday Dance", "Capture someone showing off a dance move.", "Users"],
  ["something-sparkly", "Something Sparkly", "Find the sparkliest party detail.", "Gem"],
  ["favorite-snack", "Favorite Snack", "Photograph a snack your team would choose first.", "Cookie"],
  ["make-a-wish", "Make A Wish", "Strike your best make-a-wish pose.", "Star"],
  ["party-colors", "Party Colors", "Find three things that match the party colors.", "Palette"],
  ["free", "FREE", "Free space. This one is already yours.", "Star", true],
  ["funniest-face", "Funniest Face", "Take a photo of your team's funniest faces.", "Smile"],
  ["wrapped-surprise", "Wrapped Surprise", "Find a gift, bag, bow, or wrapped surprise.", "Candy"],
  ["birthday-number", "Birthday Number", "Find or make the birthday person's new age.", "Hash"],
  ["tiny-celebration", "Tiny Celebration", "Find the smallest festive detail nearby.", "Bug"],
  ["cheers", "Party Cheers", "Raise cups or hands for a team cheers.", "CupSoda"],
  ["kind-message", "Kind Message", "Write or find a kind message for the guest of honor.", "HeartHandshake"],
  ["balloon-shape", "Balloon Shape", "Find a balloon or something shaped like one.", "Circle"],
  ["final-party-pose", "Final Party Pose", "Create one strong final team pose.", "Trophy"],
]);

const cityTasks = tasks([
  ["city-team-photo", "City Team Photo", "Take a team photo with a recognizable street scene.", "Camera"],
  ["wayfinding-sign", "Wayfinding Sign", "Find a sign that helps people navigate.", "Signpost"],
  ["local-landmark", "Local Landmark", "Photograph a recognizable local landmark.", "Landmark"],
  ["public-art", "Public Art", "Find a mural, sculpture, or creative display.", "Image"],
  ["interesting-door", "Interesting Door", "Find an entrance with unusual color or detail.", "Badge"],
  ["street-number", "Street Number", "Find a street number containing a 7.", "Hash"],
  ["city-reflection", "City Reflection", "Capture a reflection in glass, water, or metal.", "Glasses"],
  ["wheels", "City Wheels", "Find a bike, scooter, cart, or other wheels.", "Bike"],
  ["free", "FREE", "Free space. This one is already yours.", "Star", true],
  ["local-menu", "Local Menu", "Find a posted menu or food special.", "Utensils"],
  ["hidden-greenery", "Hidden Greenery", "Find a plant growing in an unexpected place.", "Leaf"],
  ["pattern-detail", "Pattern Detail", "Find an interesting repeated pattern.", "Grid3X3"],
  ["public-clock", "Public Clock", "Find a clock, timer, or schedule display.", "Clock"],
  ["something-old", "Something Old", "Find a building detail or object that looks historic.", "TreePine"],
  ["something-new", "Something New", "Find something that looks newly built or installed.", "Gem"],
  ["helpful-place", "Helpful Place", "Find a place that provides a public service.", "HeartHandshake"],
  ["transit-marker", "Transit Marker", "Find a transit stop, route marker, or station sign.", "Bus"],
  ["interesting-seat", "Interesting Seat", "Find a bench or unusual place to sit.", "Armchair"],
  ["local-mascot", "Local Mascot", "Find an animal, character, or mascot on a sign.", "Dog"],
  ["water-feature", "Water Feature", "Find a fountain, shoreline, drain, or water detail.", "Droplets"],
  ["something-round", "Something Round", "Find a round detail bigger than your hand.", "Circle"],
  ["city-texture", "City Texture", "Take a close photo of an interesting texture.", "Palette"],
  ["posted-message", "Posted Message", "Find a public notice, flyer, or message board.", "Mailbox"],
  ["team-shadow", "Team Shadow", "Photograph your team's shadows together.", "Cloud"],
  ["food-window", "Food Window", "Find a window or counter serving food or drinks.", "CupSoda"],
  ["unexpected-art", "Unexpected Art", "Find a creative detail that is easy to miss.", "Flower2"],
  ["safety-symbol", "Safety Symbol", "Find a sign or marking designed to keep people safe.", "Flag"],
  ["up-high", "Look Up", "Photograph an interesting detail above eye level.", "Bird"],
  ["down-low", "Look Down", "Find a detail on the ground most people pass by.", "Bug"],
  ["local-name", "Local Name", "Find the city or neighborhood name displayed somewhere.", "Route"],
  ["team-wave", "Team Wave", "Get the whole team waving in one photo.", "Users"],
  ["finish-landmark", "Finish Landmark", "Take a final team photo at your favorite find.", "Trophy"],
]);

const officeTasks = tasks([
  ["team-introduction", "Team Introduction", "Take a photo that shows your whole team.", "Camera"],
  ["company-colors", "Company Colors", "Find three items matching the company colors.", "Palette"],
  ["creative-workspace", "Creative Workspace", "Find the most creative desk or work area.", "Armchair"],
  ["helpful-tool", "Helpful Tool", "Find a tool people rely on to get work done.", "HardHat"],
  ["meeting-spot", "Meeting Spot", "Photograph a place where people gather or collaborate.", "Users"],
  ["tiny-office-item", "Tiny Office Item", "Find the smallest useful office item.", "Bug"],
  ["snack-stash", "Snack Stash", "Find a snack people would be happy to share.", "Cookie"],
  ["best-view", "Best View", "Find the best view from the workplace.", "Eye"],
  ["team-motto", "Team Motto", "Write a five-word motto for your team.", "Flag"],
  ["something-organized", "Something Organized", "Find a satisfyingly organized space or object.", "Grid3X3"],
  ["old-technology", "Old Technology", "Find the oldest piece of technology nearby.", "Clock"],
  ["future-idea", "Future Idea", "Stage a photo representing a big future idea.", "Star"],
  ["hidden-talent", "Hidden Talent", "Show one teammate's unexpected skill.", "Trophy"],
  ["office-plant", "Office Plant", "Find a real or artificial plant.", "Leaf"],
  ["kind-note", "Kind Note", "Leave an appropriate thank-you note for someone.", "HeartHandshake"],
  ["safety-first", "Safety First", "Find a workplace safety sign or item.", "Signpost"],
  ["team-shape", "Team Shape", "Use your team to make a recognizable shape.", "Circle"],
  ["unexpected-color", "Unexpected Color", "Find a bright color in an ordinary workspace.", "Badge"],
  ["break-time", "Break Time", "Photograph a favorite place to take a short break.", "CupSoda"],
  ["office-pattern", "Office Pattern", "Find an interesting repeated pattern.", "Gem"],
  ["shared-success", "Shared Success", "Find something that represents a team achievement.", "Goal"],
  ["final-team-pose", "Final Team Pose", "Create a confident final team photo.", "Trophy"],
]);

const kidsIndoorTasks = tasks([
  ["silly-team-name", "Silly Team Name", "Invent the silliest school-appropriate team name.", "Smile"],
  ["something-red", "Something Red", "Find something red.", "Badge"],
  ["soft-thing", "Something Soft", "Find something soft to touch.", "Cloud"],
  ["round-thing", "Something Round", "Find something shaped like a circle.", "Circle"],
  ["favorite-book", "Favorite Book", "Find a book your team would like to read.", "School"],
  ["tiny-toy", "Tiny Toy", "Find a very small toy or object.", "Bug"],
  ["animal-picture", "Animal Picture", "Find a picture or toy of an animal.", "Dog"],
  ["free", "FREE", "Free space. This one is already yours.", "Star", true],
  ["something-shiny", "Something Shiny", "Find something shiny or reflective.", "Gem"],
  ["funny-hat", "Funny Hat", "Find or make a funny hat.", "HardHat"],
  ["number-five", "Number Five", "Find the number 5.", "Hash"],
  ["building-blocks", "Building Blocks", "Build a small tower or shape.", "Grid3X3"],
  ["happy-dance", "Happy Dance", "Show your team's happiest dance move.", "Smile"],
  ["helping-hands", "Helping Hands", "Do something helpful together.", "HeartHandshake"],
  ["rainbow-colors", "Rainbow Colors", "Find three different bright colors.", "Palette"],
  ["winning-cheer", "Winning Cheer", "Invent one final quiet superhero cheer.", "Trophy"],
]);

const classroomTasks = tasks([
  ["classroom-color", "Classroom Color", "Find an object in the color your team chooses.", "Palette"],
  ["book-spine", "Book Spine", "Find a book title with an interesting word in it.", "School"],
  ["quiet-pattern", "Quiet Pattern", "Spot a repeated pattern in the room without moving anything.", "Grid3X3"],
  ["helpful-tool", "Helpful Learning Tool", "Find a tool that helps people learn or create.", "Star"],
  ["kind-word", "Kind Word", "Share one encouraging word with your team.", "HeartHandshake"],
  ["number-spot", "Number Spot", "Find a number displayed in the room.", "Hash"],
  ["shape-search", "Shape Search", "Find a circle, triangle, or rectangle nearby.", "Circle"],
  ["free", "FREE", "Free space. This one is already yours.", "Star", true],
  ["reading-spot", "Reading Spot", "Find a comfortable place where someone could read.", "Armchair"],
  ["team-signal", "Quiet Team Signal", "Invent a silent signal your team can use to regroup.", "Flag"],
  ["word-builder", "Build a Word", "Take turns adding one letter to make a word.", "Hash"],
  ["organized-space", "Organized Space", "Find something arranged in a satisfying way.", "Grid3X3"],
  ["texture-detail", "Texture Detail", "Describe an interesting texture you can see.", "Gem"],
  ["helpful-sign", "Helpful Sign", "Find a sign or label that helps people know what to do.", "Signpost"],
  ["team-story", "One-Sentence Story", "Make a sentence with each teammate adding one word.", "Users"],
  ["learning-win", "Learning Win", "Name one thing your team noticed that it had not seen before.", "Trophy"],
]);

const quickTasks = tasks([
  ["team-start", "Team Start", "Take a friendly team photo or make a quick team pose.", "Camera"],
  ["bright-color", "Bright Color", "Find a bright color that stands out.", "Palette"],
  ["helpful-sign", "Helpful Sign", "Find a sign that helps people get around.", "Signpost"],
  ["interesting-texture", "Interesting Texture", "Take a close photo of an interesting texture.", "Gem"],
  ["team-shape", "Team Shape", "Use your team to make a simple recognizable shape.", "Circle"],
  ["snack-choice", "Snack Choice", "Find a snack or food display without needing to buy anything.", "Cookie"],
  ["look-up", "Look Up", "Photograph an interesting detail above eye level.", "Bird"],
  ["reflection", "Reflection", "Capture a reflection in glass, water, or metal.", "Glasses"],
  ["free", "FREE", "Free space. This one is already yours.", "Star", true],
  ["kind-message", "Kind Message", "Find or make a short kind message for your group.", "HeartHandshake"],
  ["something-round", "Something Round", "Find something round that is bigger than your hand.", "Circle"],
  ["wheels", "Wheels", "Find a bike, cart, scooter, or other wheels.", "Bike"],
  ["repeated-pattern", "Repeated Pattern", "Find a clear repeated pattern.", "Grid3X3"],
  ["team-wave", "Team Wave", "Take a photo of everyone waving.", "Users"],
  ["plant-detail", "Plant Detail", "Find a plant, leaf, or flower without picking it.", "Leaf"],
  ["finish-high-five", "Finish High Five", "Capture a final team high five.", "Trophy"],
  ["team-jump", "Team Jump", "Take a safe mid-air team jump photo.", "Triangle"],
  ["local-landmark", "Local Landmark", "Find a recognizable public landmark or entrance sign.", "Landmark"],
  ["public-clock", "Clock Or Timer", "Find a visible clock, timer, or schedule.", "Clock"],
  ["tiny-thing", "Tiny Thing", "Find the smallest interesting object you can see.", "Bug"],
  ["tall-thing", "Tall Thing", "Find the tallest thing you can see from where you are.", "TreePine"],
  ["trash-can", "Trash Can", "Find a public trash or recycling bin.", "Trash2"],
  ["animal-image", "Animal Image", "Find an animal, animal sign, or animal-themed item.", "Dog"],
  ["food-place", "Food Place", "Find a place that serves or displays food without needing to buy anything.", "Utensils"],
  ["drink-place", "Drink Place", "Find a place where people can get a drink.", "CupSoda"],
  ["something-blue", "Something Blue", "Find something blue.", "Waves"],
  ["posted-price", "Posted Price", "Find a public posted price or ticket without showing private details.", "Ticket"],
  ["mail-or-message", "Mail Or Message", "Find a public mailbox, notice, or message board.", "Mailbox"],
  ["something-shiny", "Something Shiny", "Find something shiny or reflective.", "Gem"],
  ["team-initials", "Team Initials", "Find or safely arrange your team initials.", "Flag"],
  ["number-seven", "Number Seven", "Find the number 7 displayed somewhere.", "Hash"],
  ["someone-laughing", "Someone Laughing", "Capture a real laugh from someone in your group.", "Smile"],
  ["opposite-colors", "Opposite Colors", "Find two very different colors side by side.", "Palette"],
  ["something-heavy", "Something Heavy", "Find something that looks heavy without lifting it.", "Truck"],
  ["something-light", "Something Light", "Find something light, airy, or floating.", "Bird"],
  ["weather-detail", "Weather Detail", "Find something that shows today’s weather.", "Umbrella"],
  ["sport-or-game", "Sport Or Game", "Find sports gear, a board game, or a play area.", "Goal"],
  ["public-art", "Public Art", "Find art, decoration, or a creative display.", "Image"],
  ["transportation", "Transportation", "Find a vehicle, transit sign, or route marker.", "Bus"],
  ["friendly-team-name", "Friendly Team Name", "Invent a short, friendly name for your team.", "Smile"],
  ["final-group-shot", "Final Group Shot", "Take one strong group photo to finish the game.", "Trophy"],
  ["quiet-signal", "Quiet Signal", "Invent a silent signal your group can use to regroup.", "Flag"],
]);

const freeForAllTasks = tasks([
  ["color-pop", "Color Pop", "Photograph one bright color that stands out.", "Palette"],
  ["reflection", "Reflection", "Find a reflection in glass, water, or metal.", "Glasses"],
  ["texture-closeup", "Texture Close-Up", "Take a close photo of an interesting texture.", "Gem"],
  ["hidden-detail", "Hidden Detail", "Find a small detail most people might pass by.", "Eye"],
  ["interesting-seat", "Interesting Seat", "Find an unusual or inviting place to sit.", "Armchair"],
  ["letter-shape", "Letter Shape", "Find an object or detail shaped like a letter.", "Hash"],
  ["wayfinding", "Wayfinding", "Find an arrow, map, or sign that directs people somewhere.", "Route"],
  ["something-blue", "Something Blue", "Find something blue.", "Waves"],
  ["natural-pattern", "Natural Pattern", "Find a repeated pattern in nature or a natural material.", "Flower2"],
  ["posted-hours", "Posted Hours", "Find publicly posted opening hours or a schedule.", "Clock"],
  ["interesting-window", "Interesting Window", "Find a public-facing window with an unusual shape or detail.", "Grid3X3"],
  ["shadow-shape", "Shadow Shape", "Find a shadow with an interesting shape.", "Cloud"],
  ["public-art", "Public Art", "Find art, decoration, or a creative display.", "Image"],
  ["clock-or-timer", "Clock Or Timer", "Find a visible clock, timer, or schedule.", "Clock"],
  ["circle-detail", "Circle Detail", "Find a circular detail bigger than your hand.", "Circle"],
  ["wheels", "Wheels", "Find a bike, cart, scooter, or other wheels.", "Bike"],
  ["tall-thing", "Tall Thing", "Find the tallest thing you can see from where you are.", "TreePine"],
  ["helpful-place", "Helpful Place", "Find a place or sign connected to a public service.", "HeartHandshake"],
  ["five-word-story", "Five-Word Story", "Write or say a complete story using exactly five words.", "Smile"],
  ["snack-spot", "Snack Spot", "Find a snack or food display without buying anything.", "Cookie"],
  ["something-green", "Something Green", "Find a green detail.", "Leaf"],
  ["contrast", "Strong Contrast", "Find two very different colors side by side.", "Palette"],
  ["favorite-view", "Favorite View", "Choose the most interesting view you can see.", "Landmark"],
  ["something-old", "Something Old", "Find a detail that looks older than its surroundings.", "Clock"],
  ["something-new", "Something New", "Find something that looks newly made or installed.", "Star"],
  ["light-and-shadow", "Light And Shadow", "Find a place where light and shadow meet.", "Cloud"],
  ["public-bench", "Public Bench", "Find a public bench or seating area.", "Armchair"],
  ["interesting-door", "Interesting Door", "Find a public-facing door with an interesting color or design.", "Eye"],
  ["rough-and-smooth", "Rough And Smooth", "Find one rough surface and one smooth surface.", "Gem"],
  ["local-name", "Local Name", "Find a city, neighborhood, or venue name displayed publicly.", "Landmark"],
  ["water-detail", "Water Detail", "Find a fountain, water bottle, or other visible water detail.", "Droplets"],
  ["finish-favorite", "Finish Favorite", "Take a photo of your favorite find from the walk.", "Trophy"],
]);

const atHomeTasks = tasks([
  ["cozy-color", "Cozy Color", "Find a color that makes the room feel cozy.", "Palette"],
  ["favorite-book", "Favorite Book", "Find a book someone in the group would enjoy.", "School"],
  ["soft-thing", "Something Soft", "Find something soft to touch with permission.", "Cloud"],
  ["home-pattern", "Home Pattern", "Find a repeated pattern in the room.", "Grid3X3"],
  ["team-motto", "Team Motto", "Invent a short friendly motto for your team.", "Flag"],
  ["kitchen-color", "Kitchen Color", "Find a colorful kitchen or snack detail without making a mess.", "Cookie"],
  ["tiny-detail", "Tiny Detail", "Find the smallest interesting object you can see.", "Bug"],
  ["free", "FREE", "Free space. This one is already yours.", "Star", true],
  ["window-view", "Window View", "Describe something interesting you can see from a window.", "Eye"],
  ["family-favorite", "Family Favorite", "Have everyone name a favorite game, show, or snack.", "HeartHandshake"],
  ["circle-search", "Circle Search", "Find three circular things.", "Circle"],
  ["build-a-word", "Build A Word", "Take turns adding one letter to make a word.", "Hash"],
  ["helping-hands", "Helping Hands", "Do one helpful thing together with permission.", "HeartHandshake"],
  ["sound-guess", "Sound Guess", "Make a quiet safe sound and let the group guess its source.", "Smile"],
  ["home-treasure", "Home Treasure", "Choose an ordinary object and invent a friendly backstory for it.", "Gem"],
  ["final-cheer", "Final Cheer", "Create a quiet final cheer or celebration pose.", "Trophy"],
]);

const parkTasks = tasks([
  ["park-color", "Park Color", "Find a color that stands out in the park.", "Palette"],
  ["tree-shape", "Interesting Tree Shape", "Find a tree or branch with an unusual shape without touching it.", "TreePine"],
  ["safe-sign", "Safety Sign", "Find a sign or marking designed to keep people safe.", "Signpost"],
  ["cloud-shape", "Cloud Shape", "Find a cloud that resembles something else.", "Cloud"],
  ["park-bench", "Park Bench", "Find a bench, picnic table, or public place to sit.", "Armchair"],
  ["nature-sound", "Nature Sound", "Pause and identify one natural sound around you.", "Bird"],
  ["team-shape", "Team Shape", "Use your group to make a simple shape in an open safe area.", "Circle"],
  ["free", "FREE", "Free space. This one is already yours.", "Star", true],
  ["leaf-detail", "Leaf Detail", "Find an interesting leaf without picking it.", "Leaf"],
  ["wheels", "Wheels", "Find a bike, stroller, or other wheels from a safe distance.", "Bike"],
  ["playful-pattern", "Playful Pattern", "Find a repeated pattern on a path, fence, or play area.", "Grid3X3"],
  ["kind-choice", "Kind Choice", "Let another teammate choose the next task.", "HeartHandshake"],
  ["round-object", "Round Object", "Find something round that is bigger than your hand.", "Circle"],
  ["nature-colors", "Nature Colors", "Find three different colors in nature.", "Flower2"],
  ["look-up", "Look Up", "Find an interesting detail above eye level.", "Bird"],
  ["park-favorite", "Park Favorite", "Choose the group’s favorite park find.", "Trophy"],
]);

const neighborhoodTasks = tasks([
  ["street-name", "Street Name", "Find a public street-name sign.", "Signpost"],
  ["local-landmark", "Local Landmark", "Find a recognizable public landmark or entrance sign.", "Landmark"],
  ["wayfinding-arrow", "Wayfinding Arrow", "Find an arrow that helps people know where to go.", "Route"],
  ["interesting-door", "Interesting Door", "Find a public-facing door with an interesting color or design.", "Eye"],
  ["window-display", "Window Display", "Find a public-facing window with a memorable detail.", "Grid3X3"],
  ["neighborhood-tree", "Neighborhood Tree", "Find a tree or plant growing near a public path.", "TreePine"],
  ["public-seat", "Public Seat", "Find a bench or other public place to sit.", "Armchair"],
  ["free", "FREE", "Free space. This one is already yours.", "Star", true],
  ["local-color", "Local Color", "Photograph a bright color in a public-facing detail.", "Palette"],
  ["public-art", "Public Art", "Find art, decoration, or a creative display.", "Image"],
  ["posted-hours", "Posted Hours", "Find publicly posted opening hours or a schedule.", "Clock"],
  ["wheels", "Wheels", "Find a bike, cart, scooter, or other wheels.", "Bike"],
  ["something-round", "Something Round", "Find a round detail bigger than your hand.", "Circle"],
  ["helpful-place", "Helpful Place", "Find a public place or sign that helps the community.", "HeartHandshake"],
  ["pattern-detail", "Pattern Detail", "Photograph an interesting repeated pattern.", "Gem"],
  ["water-detail", "Water Detail", "Find a fountain, water bottle station, or other visible water detail.", "Droplets"],
  ["city-sound", "Neighborhood Sound", "Pause and name one sound that belongs to this neighborhood.", "Bus"],
  ["look-up", "Look Up", "Photograph an interesting detail above eye level.", "Bird"],
  ["look-down", "Look Down", "Find an interesting detail on the ground without blocking anyone.", "Bug"],
  ["team-wave", "Team Wave", "Take a friendly team wave photo.", "Users"],
  ["finish-landmark", "Finish Landmark", "Take a final photo at your favorite public find.", "Trophy"],
]);

const holidayDinnerTasks = tasks([
  ["table-color", "Table Color", "Find a color that makes the gathering feel festive.", "Palette"],
  ["kind-toast", "Kind Toast", "Share one short kind toast or thank-you with the group.", "HeartHandshake"],
  ["favorite-snack", "Favorite Snack", "Find a snack or dish someone is excited to try.", "Cookie"],
  ["celebration-detail", "Celebration Detail", "Find a small detail that makes the gathering feel special.", "Gem"],
  ["team-title", "Team Title", "Invent a playful, all-ages title for your team.", "Trophy"],
  ["holiday-pattern", "Holiday Pattern", "Find a repeated pattern in a decoration or table setting.", "Grid3X3"],
  ["story-starter", "Story Starter", "Have each person add one word to a cheerful story.", "Users"],
  ["free", "FREE", "Free space. This one is already yours.", "Star", true],
  ["sparkle", "Something Sparkly", "Find something shiny or reflective.", "Gem"],
  ["round-detail", "Round Detail", "Find a round object bigger than your hand.", "Circle"],
  ["thank-you-note", "Thank-You Note", "Write or find a short thank-you message.", "HeartHandshake"],
  ["music-memory", "Music Memory", "Name a song that would fit the moment without playing it.", "Smile"],
  ["family-tradition", "Friendly Tradition", "Share a favorite harmless tradition or ritual.", "Star"],
  ["color-match", "Color Match", "Find two things that are nearly the same color.", "Palette"],
  ["group-pose", "Group Pose", "Take an optional friendly group pose with permission.", "Camera"],
  ["final-cheers", "Final Cheers", "Raise hands or cups for a final team cheers.", "CupSoda"],
]);

const newTeamWelcomeTasks = tasks([
  ["name-connection", "Name Connection", "Find two people whose names share a first letter.", "Hash"],
  ["shared-hobby", "Shared Hobby", "Find two people who enjoy a similar hobby.", "Users"],
  ["team-motto", "Team Motto", "Create a five-word motto for your new team.", "Flag"],
  ["helpful-tool", "Helpful Tool", "Find a tool or resource people can use at this gathering.", "HardHat"],
  ["welcome-sign", "Welcome Sign", "Find a sign, label, or detail that helps someone feel oriented.", "Signpost"],
  ["common-ground", "Common Ground", "Name three things your team has in common.", "HeartHandshake"],
  ["creative-idea", "Creative Idea", "Invent one small idea that would make this place better.", "Star"],
  ["free", "FREE", "Free space. This one is already yours.", "Star", true],
  ["team-shape", "Team Shape", "Use your group to make a simple recognizable shape.", "Circle"],
  ["kind-note", "Kind Note", "Write or say one specific encouragement for a teammate.", "HeartHandshake"],
  ["shared-color", "Shared Color", "Find a color everyone on the team likes.", "Palette"],
  ["quiet-signal", "Quiet Signal", "Invent a quiet signal your group can use to regroup.", "Flag"],
  ["one-minute-plan", "One-Minute Plan", "Agree on your next three tasks in under one minute.", "Clock"],
  ["hidden-talent", "Hidden Talent", "Have a teammate share a safe all-ages talent.", "Trophy"],
  ["team-story", "Team Story", "Build one sentence with each person adding one word.", "Smile"],
  ["welcome-win", "Welcome Win", "Name one thing the team learned about each other.", "Trophy"],
]);

const soloPhotoWalkTasks = tasks([
  ["color-pop", "Color Pop", "Photograph one bright color that stands out.", "Palette"],
  ["reflection", "Reflection", "Find a reflection in glass, water, or metal.", "Glasses"],
  ["texture-closeup", "Texture Close-Up", "Take a close photo of an interesting texture.", "Gem"],
  ["wayfinding", "Wayfinding", "Find an arrow, map, or sign that directs people somewhere.", "Route"],
  ["public-art", "Public Art", "Find art, decoration, or a creative display.", "Image"],
  ["interesting-window", "Interesting Window", "Find a public-facing window with an unusual detail.", "Grid3X3"],
  ["something-round", "Something Round", "Find a round detail bigger than your hand.", "Circle"],
  ["look-up", "Look Up", "Photograph an interesting detail above eye level.", "Bird"],
  ["look-down", "Look Down", "Find an interesting detail on the ground without blocking anyone.", "Bug"],
  ["public-clock", "Public Clock", "Find a visible clock, timer, or schedule.", "Clock"],
  ["interesting-seat", "Interesting Seat", "Find an unusual or inviting public place to sit.", "Armchair"],
  ["wheels", "Wheels", "Find a bike, cart, scooter, or other wheels.", "Bike"],
  ["plant-detail", "Plant Detail", "Find a plant, leaf, or flower without picking it.", "Leaf"],
  ["water-detail", "Water Detail", "Find a fountain, water bottle station, or other visible water detail.", "Droplets"],
  ["shadow-shape", "Shadow Shape", "Find a shadow with an interesting shape.", "Cloud"],
  ["small-sign", "Small Sign", "Find a small public sign that most people may overlook.", "Signpost"],
  ["shape-in-architecture", "Architectural Shape", "Find a circle, triangle, or arch in a building.", "Landmark"],
  ["something-old", "Something Old", "Find a detail that looks older than its surroundings.", "Clock"],
  ["something-new", "Something New", "Find something that looks newly made or installed.", "Star"],
  ["local-name", "Local Name", "Find a city, neighborhood, or venue name displayed publicly.", "Landmark"],
  ["pattern-detail", "Pattern Detail", "Find a repeated pattern.", "Grid3X3"],
  ["safety-symbol", "Safety Symbol", "Find a sign or marking designed to keep people safe.", "Flag"],
  ["food-window", "Food Window", "Find a public-facing food or drink display without buying anything.", "CupSoda"],
  ["natural-color", "Natural Color", "Find a natural color other than green or brown.", "Flower2"],
  ["light-and-shadow", "Light And Shadow", "Find a place where light and shadow meet.", "Cloud"],
  ["interesting-door", "Interesting Door", "Find a public-facing door with an interesting color or design.", "Eye"],
  ["public-bench", "Public Bench", "Find a public bench or seating area.", "Armchair"],
  ["city-sound", "City Sound", "Pause and name one sound that belongs to the place around you.", "Bus"],
  ["favorite-view", "Favorite View", "Choose the most interesting view you can see.", "Landmark"],
  ["kind-observation", "Kind Observation", "Notice one thoughtful or helpful public detail.", "HeartHandshake"],
  ["finish-favorite", "Finish Favorite", "Take a photo of your favorite find from the walk.", "Trophy"],
  ["one-line-poem", "One-Line Poem", "Write a one-line poem inspired by something nearby.", "Flower2"],
]);

export const GAME_KITS: readonly GameKit[] = [
  {
    id: "classroom",
    name: "Classroom Starter",
    gameName: "Classroom Rally",
    category: "Schools",
    setting: "Classroom or library",
    ageLabel: "Students",
    summary: "A no-photo classroom game with simple observation and teamwork prompts.",
    detail: "Shared 3×3 boards. Students mark finds without uploading photos.",
    featured: true,
    searchTags: ["school", "teacher", "student", "classroom", "library", "no photo"],
    playerLabel: "2 teams",
    durationLabel: "30 min",
    playMode: "teams",
    winCondition: "bingo",
    boardSize: 3,
    boardMode: "shared",
    freeSpace: true,
    proofMode: "none",
    approvalMode: "automatic",
    timerMode: "duration",
    timerDurationMinutes: 30,
    teamCount: 2,
    tasks: classroomTasks,
  },
  {
    id: "quick",
    name: "Quick Bingo",
    gameName: "Quick Bingo",
    category: "Easy start",
    setting: "Anywhere",
    ageLabel: "All ages",
    summary: "A fast, low-setup game for almost any gathering.",
    detail: "Shared 3×3 boards with automatic photo approval.",
    featured: true,
    searchTags: ["quick", "easy", "general", "party", "indoor", "outdoor"],
    playerLabel: "2 teams",
    durationLabel: "30 min",
    playMode: "teams",
    winCondition: "bingo",
    boardSize: 3,
    boardMode: "shared",
    freeSpace: true,
    proofMode: "required",
    approvalMode: "automatic",
    timerMode: "duration",
    timerDurationMinutes: 30,
    teamCount: 2,
    tasks: quickTasks,
  },
  {
    id: "at-home-adventure",
    name: "At-Home Adventure",
    gameName: "At-Home Adventure",
    category: "Family",
    setting: "Home or community room",
    ageLabel: "Kids and families",
    summary: "A calm, no-photo hunt for a living room, kitchen, or rainy-day gathering.",
    detail: "Shared 3×3 boards with simple prompts and no photo uploads.",
    searchTags: ["home", "family", "indoor", "rainy day", "kids", "no photo"],
    playerLabel: "2 teams",
    durationLabel: "30 min",
    playMode: "teams",
    winCondition: "bingo",
    boardSize: 3,
    boardMode: "shared",
    freeSpace: true,
    proofMode: "none",
    approvalMode: "automatic",
    timerMode: "duration",
    timerDurationMinutes: 30,
    teamCount: 2,
    tasks: atHomeTasks,
  },
  {
    id: "free-for-all",
    name: "Free-for-All",
    gameName: "Free-for-All Hunt",
    category: "Individuals",
    setting: "Anywhere",
    ageLabel: "Teens and adults",
    summary: "Everyone plays on a personal board at their own pace.",
    detail: "Different 4×4 boards with optional photos.",
    searchTags: ["solo", "individual", "personal", "casual", "general"],
    playerLabel: "Individual",
    durationLabel: "45 min",
    playMode: "individual",
    winCondition: "bingo",
    boardSize: 4,
    boardMode: "randomized",
    freeSpace: false,
    proofMode: "optional",
    approvalMode: "automatic",
    timerMode: "duration",
    timerDurationMinutes: 45,
    teamCount: 0,
    tasks: freeForAllTasks,
  },
  {
    id: "birthday-party",
    name: "Birthday Party",
    gameName: "Birthday Party Hunt",
    category: "Celebration",
    setting: "Indoor or outdoor",
    ageLabel: "All ages",
    summary: "Playful photo challenges built around the guest of honor.",
    detail: "Different 3×3 boards that work indoors or outside.",
    featured: true,
    searchTags: ["birthday", "party", "celebration", "family", "photo"],
    playerLabel: "2 teams",
    durationLabel: "45 min",
    playMode: "teams",
    winCondition: "bingo",
    boardSize: 3,
    boardMode: "randomized",
    freeSpace: true,
    proofMode: "required",
    approvalMode: "automatic",
    timerMode: "duration",
    timerDurationMinutes: 45,
    teamCount: 2,
    tasks: birthdayTasks,
  },
  {
    id: "holiday-dinner",
    name: "Holiday & Dinner Gathering",
    gameName: "Holiday & Dinner Gathering",
    category: "Celebration",
    setting: "Home, dinner, or celebration",
    ageLabel: "All ages",
    summary: "A warm, low-pressure game for dinner tables, holidays, and family get-togethers.",
    detail: "Varied 3×3 boards with optional photos and automatic approval.",
    searchTags: ["holiday", "dinner", "celebration", "family", "party", "indoor", "optional photos"],
    playerLabel: "2 teams",
    durationLabel: "45 min",
    playMode: "teams",
    winCondition: "bingo",
    boardSize: 3,
    boardMode: "randomized",
    freeSpace: true,
    proofMode: "optional",
    approvalMode: "automatic",
    timerMode: "duration",
    timerDurationMinutes: 45,
    teamCount: 2,
    tasks: holidayDinnerTasks,
  },
  {
    id: "city-explorer",
    name: "City Explorer",
    gameName: "City Explorer Hunt",
    category: "Outdoors",
    setting: "City or neighborhood",
    ageLabel: "Teens and adults",
    summary: "A longer hunt for downtowns, boardwalks, or neighborhoods.",
    detail: "Varied 5×5 boards with host-reviewed photo proof.",
    searchTags: ["city", "downtown", "outdoor", "travel", "neighborhood", "long"],
    playerLabel: "3 teams",
    durationLabel: "90 min",
    playMode: "teams",
    winCondition: "blackout",
    boardSize: 5,
    boardMode: "randomized",
    freeSpace: true,
    proofMode: "required",
    approvalMode: "host",
    timerMode: "duration",
    timerDurationMinutes: 90,
    teamCount: 3,
    tasks: cityTasks,
  },
  {
    id: "neighborhood-stroll",
    name: "Neighborhood Stroll",
    gameName: "Neighborhood Stroll",
    category: "Outdoors",
    setting: "Neighborhood or main street",
    ageLabel: "All ages",
    summary: "A shorter, gentler outdoor hunt for a familiar block or nearby town center.",
    detail: "Varied 3×3 boards with optional photos and automatic approval.",
    searchTags: ["neighborhood", "outdoor", "walk", "town", "main street", "city", "optional photos"],
    playerLabel: "2 teams",
    durationLabel: "45 min",
    playMode: "teams",
    winCondition: "bingo",
    boardSize: 3,
    boardMode: "randomized",
    freeSpace: true,
    proofMode: "optional",
    approvalMode: "automatic",
    timerMode: "duration",
    timerDurationMinutes: 45,
    teamCount: 2,
    tasks: neighborhoodTasks,
  },
  {
    id: "park-playground",
    name: "Park & Playground",
    gameName: "Park & Playground Hunt",
    category: "Outdoors",
    setting: "Park or playground",
    ageLabel: "Kids and families",
    summary: "A simple outdoor game built around noticing, listening, and playing safely together.",
    detail: "Shared 3×3 boards with no photo uploads.",
    searchTags: ["park", "playground", "outdoor", "kids", "family", "nature", "no photo"],
    playerLabel: "2 teams",
    durationLabel: "30 min",
    playMode: "teams",
    winCondition: "bingo",
    boardSize: 3,
    boardMode: "shared",
    freeSpace: true,
    proofMode: "none",
    approvalMode: "automatic",
    timerMode: "duration",
    timerDurationMinutes: 30,
    teamCount: 2,
    tasks: parkTasks,
  },
  {
    id: "office-team-building",
    name: "Office Team-Building",
    gameName: "Office Team-Building Hunt",
    category: "Work",
    setting: "Office or workplace",
    ageLabel: "Adults",
    summary: "Friendly challenges that reward teamwork and observation.",
    detail: "Different 4×4 boards with optional photo proof.",
    searchTags: ["office", "work", "company", "team building", "coworkers"],
    playerLabel: "3 teams",
    durationLabel: "60 min",
    playMode: "teams",
    winCondition: "bingo",
    boardSize: 4,
    boardMode: "randomized",
    freeSpace: false,
    proofMode: "optional",
    approvalMode: "automatic",
    timerMode: "duration",
    timerDurationMinutes: 60,
    teamCount: 3,
    tasks: officeTasks,
  },
  {
    id: "new-team-welcome",
    name: "New Team Welcome",
    gameName: "New Team Welcome",
    category: "Work",
    setting: "Office, retreat, or meetup",
    ageLabel: "Teens and adults",
    summary: "A no-photo icebreaker for people getting to know a new group.",
    detail: "Shared 3×3 boards focused on names, common ground, and simple collaboration.",
    searchTags: ["work", "welcome", "onboarding", "orientation", "icebreaker", "meetup", "no photo"],
    playerLabel: "2 teams",
    durationLabel: "30 min",
    playMode: "teams",
    winCondition: "bingo",
    boardSize: 3,
    boardMode: "shared",
    freeSpace: true,
    proofMode: "none",
    approvalMode: "automatic",
    timerMode: "duration",
    timerDurationMinutes: 30,
    teamCount: 2,
    tasks: newTeamWelcomeTasks,
  },
  {
    id: "kids-indoor",
    name: "Kids’ Indoor Hunt",
    gameName: "Kids’ Indoor Hunt",
    category: "Family",
    setting: "Home or classroom",
    ageLabel: "Kids and families",
    summary: "Simple, safe prompts for homes, classrooms, or community rooms.",
    detail: "Shared 3×3 boards with no photo uploads.",
    featured: true,
    searchTags: ["kids", "children", "family", "classroom", "home", "indoor"],
    playerLabel: "2 teams",
    durationLabel: "30 min",
    playMode: "teams",
    winCondition: "bingo",
    boardSize: 3,
    boardMode: "shared",
    freeSpace: true,
    proofMode: "none",
    approvalMode: "automatic",
    timerMode: "duration",
    timerDurationMinutes: 30,
    teamCount: 2,
    tasks: kidsIndoorTasks,
  },
  {
    id: "solo-photo-walk",
    name: "Solo Photo Walk",
    gameName: "Solo Photo Walk",
    category: "Individuals",
    setting: "Neighborhood, park, or city",
    ageLabel: "Teens and adults",
    summary: "A personal, at-your-own-pace walk for noticing the small details around you.",
    detail: "Different 4×4 boards with optional photos and automatic approval.",
    searchTags: ["solo", "individual", "photo walk", "outdoor", "city", "neighborhood", "optional photos"],
    playerLabel: "Individual",
    durationLabel: "45 min",
    playMode: "individual",
    winCondition: "bingo",
    boardSize: 4,
    boardMode: "randomized",
    freeSpace: false,
    proofMode: "optional",
    approvalMode: "automatic",
    timerMode: "duration",
    timerDurationMinutes: 45,
    teamCount: 0,
    tasks: soloPhotoWalkTasks,
  },
];

export function getGameKit(id: string) {
  return GAME_KITS.find((kit) => kit.id === id);
}

function tasks(
  values: ReadonlyArray<readonly [string, string, string, string, boolean?]>,
): readonly GameKitTask[] {
  return values.map(([id, title, description, icon, free], index) => ({
    id,
    title,
    description,
    icon,
    sortOrder: index + 1,
    ...(free ? { free: true } : {}),
  }));
}
